language: python
sudo: required
services:
  - docker

branches:
  - master
python:
  - '2.7'
install:
  - pip install pycodestyle
  - pip install flake8
script:
  - pycodestyle --max-line-length=100 .
  - make debug
  - make test
