language: python

sudo: required

services:
  - docker

python:
  - "2.7"

install:
  - pip install flake8

script:
  - flake8 .
  - docker-compose build
  - docker-compose up
  - sleep 5
  - make test
