"""empty message

Revision ID: 10df8481ea33
Revises: 82624bc39c53
Create Date: 2016-12-01 22:58:34.478355

"""

# revision identifiers, used by Alembic.
revision = '10df8481ea33'
down_revision = '82624bc39c53'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('validation_message', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'validation_message')
    ### end Alembic commands ###
