"""empty message

Revision ID: 5f29bdd88ffd
Revises: f27abdb911b1
Create Date: 2017-01-07 22:39:28.756975

"""

# revision identifiers, used by Alembic.
revision = '5f29bdd88ffd'
down_revision = 'f27abdb911b1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('validation_details', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'validation_details')
    ### end Alembic commands ###
