"""empty message

Revision ID: 7656388ae199
Revises: 5f29bdd88ffd
Create Date: 2017-02-02 21:24:08.819684

"""

# revision identifiers, used by Alembic.
revision = '7656388ae199'
down_revision = '5f29bdd88ffd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('user', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'user')
    ### end Alembic commands ###
