"""empty message

Revision ID: 8109524d975b
Revises: None
Create Date: 2016-11-10 01:28:05.938913

"""

# revision identifiers, used by Alembic.
revision = '8109524d975b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('new', 'received', 'validated', 'invalid', 'signed'), nullable=True),
    sa.Column('receipt_text', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submission')
    ### end Alembic commands ###
