"""empty message

Revision ID: 821cf7c98570
Revises: None
Create Date: 2016-11-01 12:03:44.378374

"""

# revision identifiers, used by Alembic.
revision = '821cf7c98570'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submission')
    ### end Alembic commands ###
