"""empty message

Revision ID: 82624bc39c53
Revises: None
Create Date: 2016-11-15 22:45:49.143187

"""

# revision identifiers, used by Alembic.
revision = '82624bc39c53'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('new', 'received', 'validated', 'invalid', 'signed'), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('receipt', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submission')
    ### end Alembic commands ###
