"""empty message

Revision ID: f27abdb911b1
Revises: None
Create Date: 2016-12-08 03:46:15.657551

"""

# revision identifiers, used by Alembic.
revision = 'f27abdb911b1'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('receipt', sa.Text(), nullable=True),
    sa.Column('validation_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submission')
    ### end Alembic commands ###
